import styles from "./About.module.css";

const AboutAsterClinic = () => {
  return (
    <>
         <div className="container">
      <div className="row">
        <div className="col-lg-11 mx-auto text-justify mb-5 pb-4">
        <h3 className={`${styles.titleBorder} ${styles.secTitle}`}>
        ABOUT ASTER CLINIC
        </h3>

        <div className="col-xs-12 col-sm-12 col-md-12 about-block mb-5">
					<p className={`mgmt-name ${styles.para}`}>A NETWORK OF WORLD-CLASS CLINICS THAT BRING QUALITY CARE TO EVERY NEIGHBOURHOOD.</p>
<p className={` ${styles.para}`}>When the first Aster Clinic was established in 1987, little did we know that it would grow into one of the largest network of clinics across the Middle East.&nbsp; We have spent the last 3 decades in strengthening the scope and quality of our services while simultaneously evolving the brand, to ensure that all our patient’s healthcare needs are met.</p>
<p className={` ${styles.para}`}>Not only is Aster Clinic now one of the biggest integrated networks in the region, but we have also successfully reshaped the healthcare landscape across each of the neighborhoods that we operate in.&nbsp; Placing our patients at the heart of our operations, we have developed robust quality standards, enhanced professional expertise and built spacious infrastructures to render the most comfortable and satisfying experience for all our patients.</p>
<p className={` ${styles.para}`}>Bringing together these elements, we have set the benchmark for healthcare in the region. As the years have gone by, we have added more clinics to keep up with the demand generated by the growing trust that is placed in Aster Clinic.</p>
				</div>
        </div>
      </div>
    </div>
    </>
  )
}

export default AboutAsterClinic